### ISSUE TITLE
 annotation tools

### ISSUE THREAD

**Issue by GodsDusk** [NUSTM/ACOS#13]
good work for me.

besides, Are there any open-source annotation tools to annotate quadruple data?

**Comment by blhoy** [comment]
I would recommend using Inception (https://inception-project.github.io/downloads/) to annotate quadruple data.

**Comment by GodsDusk** [comment]
> I would recommend using Inception (https://inception-project.github.io/downloads/) to annotate quadruple data.

I see Inception is an entity and relation annotation tool, but how to use it to annotate implicit aspects and opinions?

**Comment by blhoy** [comment]
> 

Two special tags can be used to indicate implicit aspects and opinions.
