### ISSUE TITLE
如何使用训练好的模型进行预测

### ISSUE THREAD

**Issue by VohsiLiu** [NUSTM/ACOS#16]
您好，请问当我完成训练后，如何使用已经训练好的模型进行预测其他数据，预测数据的格式应该是怎么样的。

**Comment by VohsiLiu** [comment]
期望得到您的回复

**Comment by blhoy** [comment]
> 您好，请问当我完成训练后，如何使用已经训练好的模型进行预测其他数据，预测数据的格式应该是怎么样的。

您好，对于step 1，需要准备好 domain_type +'_test_quad_bert.tsv' 格式的测试集；接着执行 get_1st_pairs.py脚本；对于step 2，需要有 domain_type+'_test_pair.tsv'格式的测试集。

这些内容在run_step1.py和run_step2.py数据集预处理部分可以看到。

**Comment by VohsiLiu** [comment]
感谢您的回复，上面的问题我没表达清楚，让您产生误解我深感抱歉。我的意思是在完成step1和stpe2的训练后会得到一个pytorch_model.bin文件，能否再调用这个训练好的模型对未进行标注的数据进行预测。您提到的domain_type +'_test_quad_bert.tsv' 格式的测试集是需要标注ACOS数据的，那么能否通过只输入一句话来获取模型标注好的ACOS值？谢谢。

**Comment by VohsiLiu** [comment]
> > 您好，请问当我完成训练后，如何使用已经训练好的模型进行预测其他数据，预测数据的格式应该是怎么样的。
> 
> 您好，对于step 1，需要准备好 domain_type +'_test_quad_bert.tsv' 格式的测试集；接着执行 get_1st_pairs.py脚本；对于step 2，需要有 domain_type+'_test_pair.tsv'格式的测试集。
> 
> 这些内容在run_step1.py和run_step2.py数据集预处理部分可以看到。

感谢您的回复，上面的问题我没表达清楚，让您产生误解我深感抱歉。我的意思是在完成step1和stpe2的训练后会得到一个pytorch_model.bin文件，能否再调用这个训练好的模型对未进行标注的数据进行预测。您提到的domain_type +'_test_quad_bert.tsv' 格式的测试集是需要标注ACOS数据的，那么能否通过只输入一句话来获取模型标注好的ACOS值？谢谢。

**Comment by blhoy** [comment]
> > > 您好，请问当我完成训练后，如何使用已经训练好的模型进行预测其他数据，预测数据的格式应该是怎么样的。
> > 
> > 
> > 您好，对于step 1，需要准备好 domain_type +'_test_quad_bert.tsv' 格式的测试集；接着执行 get_1st_pairs.py脚本；对于step 2，需要有 domain_type+'_test_pair.tsv'格式的测试集。
> > 这些内容在run_step1.py和run_step2.py数据集预处理部分可以看到。
> 
> 感谢您的回复，上面的问题我没表达清楚，让您产生误解我深感抱歉。我的意思是在完成step1和stpe2的训练后会得到一个pytorch_model.bin文件，能否再调用这个训练好的模型对未进行标注的数据进行预测。您提到的domain_type +'_test_quad_bert.tsv' 格式的测试集是需要标注ACOS数据的，那么能否通过只输入一句话来获取模型标注好的ACOS值？谢谢。

这种可以不加args里的do_train，然后将args里的bert_model换成保存pytorch_model.bin文件的位置就可以直接预测。

**Comment by VohsiLiu** [comment]
感谢您，已经解决了。
