### ISSUE TITLE
Issues for get_1st_pairs.py

### ISSUE THREAD

**Issue by hustlihaomin** [NUSTM/ACOS#4]
你好，在ACOS/Extract-Classify-ACOS/tokenized_data/get_1st_pairs.py 的第15行中使用的pred4pipeline.txt缺失，请问是否可以提供？

**Comment by blhoy** [comment]
pred4pipeline.txt是一阶段的预测结果，具体位置在：
https://github.com/NUSTM/ACOS/blob/c7c8e3f4f5d52410eaccd55628f9928aa1699e7d/Extract-Classify-ACOS/run.sh#L22
另，输出处理后的存放路径已更正：
https://github.com/NUSTM/ACOS/blob/c7c8e3f4f5d52410eaccd55628f9928aa1699e7d/Extract-Classify-ACOS/tokenized_data/get_1st_pairs.py#L16

**Comment by hustlihaomin** [comment]
明白了，谢谢！
