### ISSUE TITLE
请问第一阶段预测出来的CRF结果中的aspect和opinion怎么配对的？

### ISSUE THREAD

**Issue by Heart-beatsss** [NUSTM/ACOS#5]
bert结果输入CRF后，得到标注序列，但是怎么从标注序列中的aspect和opinion中找到相应的对呢？请问可以指出你们代码中实现的逻辑过程吗？我找了很久都没找到

**Comment by Heart-beatsss** [comment]
我好像找到了。就是第一阶段是不管aspect-opinion对的事情，把所有的aspect和opinion组合后，丢给第二阶段去做。并且在第二阶段中，实际训练过程中，无效的aspect-opinion对的target为[0]*len(类别*情感种类)；有效对的target则为[0]*len(类别*情感种类-1)+[1]，当然这个1的位置是视目标位置而定的，我这么写只是为了区分。
如果我的想法有错误的话，还麻烦指正。期待你的回复！

**Comment by Heart-beatsss** [comment]
上述的×号丢失了。
我好像找到了。就是第一阶段是不管aspect-opinion对的事情，把所有的aspect和opinion组合后，丢给第二阶段去做。并且在第二阶段中，实际训练过程中，无效的aspect-opinion对的target为[0]×len(category×情感种类)；有效对的target则为[0]×len(category×情感种类-1)+[1]，当然这个1的位置是视目标位置而定的，我这么写只是为了区分。
如果我的想法有错误的话，还麻烦指正。期待你的回复！

**Comment by blhoy** [comment]
是这样的。一阶段得到aspect集合和opinion集合，对两个集合做笛卡尔积处理：https://github.com/NUSTM/ACOS/blob/d522a0baa6659c36215b925daeff9928980baf85/Extract-Classify-ACOS/tokenized_data/get_1st_pairs.py#L40-L44
二阶段判断aspect和opinion是否构成合法配对（全0为无效配对），并为每个合法的匹配做category-sentiment的分类（对应位置为1）。

**Comment by Heart-beatsss** [comment]
> 是这样的。一阶段得到aspect集合和opinion集合，对两个集合做笛卡尔积处理：
> 
> https://github.com/NUSTM/ACOS/blob/d522a0baa6659c36215b925daeff9928980baf85/Extract-Classify-ACOS/tokenized_data/get_1st_pairs.py#L40-L44
> 
> 
> 二阶段判断aspect和opinion是否构成合法配对（全0为无效配对），并为每个合法的匹配做category-sentiment的分类（对应位置为1）。


好的，非常感谢！
