### ISSUE TITLE
关于数据集的疑问

### ISSUE THREAD

**Issue by 20174376** [NUSTM/ACOS#8]
i had a great time at jekyll and hyde !	6,9 RESTAURANT#GENERAL 2 3,4
您好， 我想问一下这句话当中这个，6,9,2,3,4每个数字它代表的含义是什么呀？

**Comment by fikadata** [comment]
Those numbers are positions of aspects or opinions. For example words from 6 to 9 are representing aspect (jekyll and hyde). RESTAURANT#GENERAL is category, number after category is representing sentiment (in this case 2) and word from 3rd to 4th position is opinion (great). 
i(0) had(1) a(2) great(3) time(4) at(5) and so on...

**Comment by 20174376** [comment]
> Those numbers are positions of aspects or opinions. For example words from 6 to 9 are representing aspect (jekyll and hyde). RESTAURANT#GENERAL is category, number after category is representing sentiment (in this case 2) and word from 3rd to 4th position is opinion (great). i(0) had(1) a(2) great(3) time(4) at(5) and so on...

I see, thank you very much!
